global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Remove or comment out this job - the website itself doesn't expose metrics
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['website:80']
  #   metrics_path: /metrics

  # This is the correct job for nginx metrics via the exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']